version: "3"
services:
  node:
    build:
      context: .
      dockerfile: ./src/deploy/node.dockerfile
    environment:
      PORT: 8000
      POSTGRES_HOST: "postgres"
    ports:
      - "8000:8000"
    networks:
      - chatter-network

  postgres:
    build:
      context: .
      dockerfile: ./src/deploy/postgres.dockerfile
    environment:
      POSTGRES_USER: "chatter"
      POSTGRES_PASSWORD: "password"
    networks:
      - chatter-network

  coturn:
    image: coturn/coturn:4.5.2
    restart: always
    network_mode: "host"
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf

networks:
  chatter-network:
    driver: bridge
